title: 伍达辉的个人网站
SEOTitle: 伍达辉的个人网站
email: 16621177880@163.com
description: 与你一起记录精彩的世界。
keyword: "达辉, 伍达辉, 伍达辉的博客, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wudahui712-github-io.vercel.app" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
